[LF-32/article-list] 기사 목록을 전달하는 API 구현 완료
Live-Feed/live-feed-backend pull request #18
Opened 2023-11-06 08:59 UTC by jin-mook

- 코드 리팩터링 필요
* rest api 형식은 아래와 같습니다.
    * GET http://localhost:8084/api/list/articles?type=bodyHtml,articleTitle&keyword=SSG,손흥민&size=4&sort=id-desc
    * type에는 제목에서 찾는다면 articleTitle, 본문에서 찾는다면 bodyHtml 을 컴마를 통해 작성해주면 됩니다.
    * keyword에는 찾고자 하는 단어를 컴마를 통해 작성해주면 됩니다.
    * size는 기본으로 10개를 default 값이고 받는 값에 따라 달라집니다.
    * 정렬 순서는 id 기준 내림차순이기 때문에 - 기호를 통해 나타냅니다.
    * 처음 요청 이후 다음 요청에는 첫 요청에 전달받은 pit 값을 같이 보내주어야 합니다.
    * 처음 요청 이후 스크롤 요청에는 첫 요청에 전달받은 lastId 값을 같이 보내주어야 합니다.

2023-11-06 09:30 UTC, jin-mook commented
ArticleListController 에 대한 컨트롤러 테스트 필요합니다.

2023-11-08 04:57 UTC, yhwcs requested changes
사소한 수정 요청 건이 있어 확인 부탁드립니다~

2023-11-08 04:57 UTC, yhwcs commented on LiveFeedSaver/src/main/java/com/livefeed/livefeedsaver/elasticsearch/configuration/ElasticsearchClientConfig.java
> +                .connectedTo("localhost:9200")
Spring profile별로 hostAndPort 값을 분리 지정하는 것을 제안드립니다.

2023-11-08 04:57 UTC, yhwcs commented on LiveFeedService/src/main/java/com/livefeed/livefeedservice/elasticsearch/configuration/ElasticsearchClientConfig.java
> +                .connectedTo("localhost:9200")
Spring profile별로 hostAndPort 값을 분리 지정하는 것을 제안드립니다.

2023-11-08 04:57 UTC, yhwcs commented on LiveFeedService/src/test/java/com/livefeed/livefeedservice/articledetail/controller/ArticleDetailControllerTest.java
> +import com.livefeed.livefeedservice.articlelist.service.ArticleListService;
사용하지 않는 import문 제거 요청드립니다.

2023-11-08 04:57 UTC, yhwcs commented on LiveFeedService/src/test/java/com/livefeed/livefeedservice/articledetail/controller/ArticleDetailControllerTest.java
> +import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
사용하지 않는 import문 제거 요청드립니다.

2023-11-08 04:57 UTC, yhwcs commented on LiveFeedService/src/test/java/com/livefeed/livefeedservice/articlelist/controller/ArticleListControllerTest.java
> +    private ArticleDetailService articleDetailService;
테스트코드는 아직 작성 진행 중인가요?

2023-11-08 10:04 UTC, jin-mook commented on LiveFeedSaver/src/main/java/com/livefeed/livefeedsaver/elasticsearch/configuration/ElasticsearchClientConfig.java
> +                .connectedTo("localhost:9200")
네~~ yaml 파일에 따로 값 받도록 수정하겠습니다~~

2023-11-08 10:05 UTC, jin-mook commented on LiveFeedService/src/test/java/com/livefeed/livefeedservice/articlelist/controller/ArticleListControllerTest.java
> +    private ArticleDetailService articleDetailService;
지금 로직상 조금 수정할 부분이 있어서 계속 수정하고 있습니다
수정 후 테스트 코드까지 작성해서 commit 한번 더 진행 예정입니다

2023-11-10 13:43 UTC, jin-mook commented
위에 댓글 남긴 부분까지 전부 완료해서 push 했습니다~~

2023-11-12 07:40 UTC, yhwcs approved these changes
확인했습니다. 👍

2023-11-12 07:40 UTC, yhwcs commented on LiveFeedService/src/main/java/com/livefeed/livefeedservice/articlelist/domain/SearchHitModifier.java
> +
의미 없는 LF…

2023-11-12 07:40 UTC, merged