[LF-9/crawler] 구글 뉴스 크롤러 개발 및 Spring Batch, Spring Scheduler 적용
Live-Feed/live-feed-backend pull request #6
Opened 2023-08-28 09:24 UTC by yhwcs

- Selenium을 이용하여 구글 뉴스 크롤러 개발
스크롤이 더 이상 내려가지 않을 때까지 구글 뉴스 페이지의 기사 url을 읽어 kafka에 전송하도록 구현
- Spring Batch Chunk 방식 적용: url 10개 단위 실행
- Spring Scheduler 적용: 5분 단위 실행
- Spring Batch Job, Step, ItemReader, ItemWriter 단위 테스트 작성

2023-08-28 12:00 UTC, Jin-Mook requested changes

2023-08-28 12:00 UTC, jin-mook commented on LiveFeedCrawler/build.gradle
>      implementation 'org.springframework.boot:spring-boot-starter-web'
필요 없는 라이브러리 삭제해주세요~~
- kafka 관련 라이브러리는 common에 있어서 없어도 괜찮을겁니다

2023-08-29 09:23 UTC, yhwcs commented on LiveFeedCrawler/build.gradle
>      implementation 'org.springframework.boot:spring-boot-starter-web'
삭제 완료했습니다.

2023-08-29 09:28 UTC, Jin-Mook approved these changes
확인했습니다~~👍

2023-08-29 09:28 UTC, merged